### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by jackkinsella** [adamniedzielski/test-book#1]
When running `mix escript.build` from test-book I get the following message

```
➜  test-book git:(master) mix escript.build
** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available
```

I also tried running the same command from the headings folder and got no output

Finally, I tried running `sh build`from the test-book folder and that created the HTML and the PDF (but not the others). Output was as follows

```
pandoc: metadata.md: openFile: does not exist (No such file or directory)
```

**Comment by adamniedzielski** [comment]
I'm sorry for all the shortcomings of this description.

`mix escript.build` should be run from the `headings` folder. It may be necessary to run `mix deps.get` (Elixir version of `bundle install`) first. I will move this part of the description to the `headings` repo once everything is stable.

I renamed `metadata.md` to `epub_metadata.md` so the build script became outdated. It will soon be replaced by the proper build tool.

**Comment by jackkinsella** [comment]
ok no worries at all. It is still very much a spike and I am aware of that :)

**Comment by adamniedzielski** [comment]
This issue is not longer relevant - see https://github.com/adamniedzielski/admission for the new build toolchain.
